### ISSUE TITLE
lena5min error

### ISSUE THREAD

**Issue by URBabylab** [SeedlingsBabylab/audiowords#13]
This weird phenomenon is caused by the 21_10_lena5min.csv file. The first error:

![error1](https://cloud.githubusercontent.com/assets/11462259/10198882/10ad2152-676c-11e5-9472-d630cb7b5074.PNG)

This occurs because, for some reason, the last cell of the lena5min file has a duration of 0.00. I deleted this cell manually, but then this error occurs:

![error 2](https://cloud.githubusercontent.com/assets/11462259/10198933/4a850570-676c-11e5-9683-95c04f681b37.PNG)

There is something weird going on in the lena5min file and I need to run for now. Someone is working on this tomorrow so it's not suuuper urgent. 

I tried using another lena5min file (from another subject) and audiowords ran smoothly, but we need to use this lena5min file... Everything is on Lily/Desktop/Munna/21_10 but can attach via email if needed.

**Comment by ebergelson** [comment]
Did you delete ust that cell or the whole line? The other things I'd try is
giving the cell duration 1s instead of 0s and see if it goes through
(unless Andrei has other suggestions)
e

_Elika Bergelson, PhD_
Research Assistant Professor, University of Rochester
Center for Language Sciences | Brain and Cognitive Science Dept. |
www.bcs.rochester.edu/people/ebergelson | www.bcs.rochester.edu/seedlings/
Get a signature like this: Click here!
http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=

**Comment by andreiamatuni** [comment]
setting the cell duration to 1s might take care of this. if not, I'll come through the lab today and check it out (after exam at 3)

**Comment by URBabylab** [comment]
That's not working :(, would be best if you can come in sorry to disturb during exam time!

**Comment by andreiamatuni** [comment]
fixed with e435718d9aa7b8d220bdb96fc322ebbb19511192
